---
- name: "Installation des d√©pendances requises pour GitLab"
  apt:
            name: "curl, openssh-server, ca-certificates, python-openssl"
            state: present
            update-cache: yes

